a = int(input("Enter number a: "))
b = int(input("Enter number b: "))

print("The value of",a, "+",b, "=", a+b)
print("The value of",a, "-",b, "=", a-b)
print("The value of",a, "*",b, "=", a*b)
print("The value of",a, "/",b, "=", a/b)
print("The value of",a, "%",b, "=", a%b)
print("The value of",a, "**",b, "=", a**b)
print("The value of",a, "//",b, "=", a//b)